# Generated by Django 5.0.4 on 2024-04-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='DisplayName',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='BloodGroup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='DateOfBirth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='Fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='Lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='ProfilePicture',
            field=models.ImageField(null=True, upload_to='media/ProfilePic'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='UserType',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('jobseeker', 'JobSeeker')], max_length=100, null=True),
        ),
    ]
