# Generated by Django 5.0.4 on 2024-04-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_customusermodel_bloodgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('CompanyDescription', models.CharField(max_length=100)),
                ('JobDescription', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('SalaryInformation', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
            ],
        ),
    ]
