# Generated by Django 5.0.4 on 2024-04-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_addjobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjobmodel',
            name='Deadline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='CompanyDescription',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='CompanyName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='JobDescription',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='JobTitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='SalaryInformation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
