# Generated by Django 5.0.4 on 2024-04-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_addjobmodel_deadline_alter_addjobmodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjobmodel',
            name='OwnerOfJobPost',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
