# Generated by Django 5.0.4 on 2024-04-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePic', models.ImageField(upload_to='media/Image')),
                ('Name', models.CharField(max_length=100)),
                ('Roll', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
            ],
        ),
    ]
