# Generated by Django 5.0.4 on 2024-04-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Roll', models.CharField(max_length=100)),
                ('Dept', models.CharField(max_length=100)),
            ],
        ),
    ]
