# Generated by Django 5.0.4 on 2024-04-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('proficiency', models.CharField(max_length=100)),
            ],
        ),
    ]
