# Generated by Django 5.0.4 on 2024-04-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='Img',
            field=models.ImageField(null=True, upload_to='media/StudentImage'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='Roll',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
